export const authText = {
  login: {
    title: 'Welcome back',
    subtitle: 'Login to continue to your account',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    forgotPassword: 'Forgot Password?',
    submit: 'Login',
    divider: 'or continue with',
    footerLabel: 'Do not have an account?',
    footerAction: 'Sign up',
    showPassword: 'Show',
    hidePassword: 'Hide',
  },
  register: {
    title: 'Create Account',
    subtitle: 'Fill in the details below to get started',
    fullNamePlaceholder: 'Full Name',
    emailPlaceholder: 'Email Address',
    passwordPlaceholder: 'Password',
    confirmPasswordPlaceholder: 'Confirm Password',
    passwordRulesTitle: 'Password must contain:',
    submit: 'Create Account',
    divider: 'or',
    footerLabel: 'Already have an account?',
    footerAction: 'Login',
  },
  forgotPassword: {
    title: 'Forgot Password?',
    subtitle:
      "No worries! Enter your email address and we'll send you a link to reset your password.",
    emailLabel: 'Email Address',
    emailPlaceholder: 'Enter your email address',
    infoTitle: 'How it works',
    infoDescription:
      "We'll send a password reset link to your email. Click the link and create a new password.",
    submit: 'Send Reset Link',
    divider: 'or',
    supportAction: 'Need help? Contact Support',
    footerLabel: 'Remember your password?',
    footerAction: 'Login',
  },
  social: {
    google: 'Google',
    apple: 'Apple',
    signUpWithGoogle: 'Sign up with Google',
    signUpWithApple: 'Sign up with Apple',
  },
  passwordRules: {
    minLength: 'At least 8 characters',
    uppercase: 'One uppercase letter',
    lowercase: 'One lowercase letter',
    number: 'One number',
    specialCharacter: 'One special character',
  },
  validation: {
    fullNameRequired: 'Full name is required',
    fullNameMinLength: 'Full name must be at least 2 characters',
    emailRequired: 'Email address is required',
    emailInvalid: 'Enter a valid email address',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 8 characters',
    passwordUppercase: 'Password must include one uppercase letter',
    passwordLowercase: 'Password must include one lowercase letter',
    passwordNumber: 'Password must include one number',
    passwordSpecialCharacter: 'Password must include one special character',
    confirmPasswordRequired: 'Confirm password is required',
    passwordsDoNotMatch: 'Passwords do not match',
  },
};
